Let mkinitramfs fail if the utilities are missing.
The zfs-initramfs package directly depends on the zfsutils package,
so utilities in the COPY_EXEC_LIST should always be available.

Unlike some other initramfs hooks, we aren't currently detecting
whether anything in /sbin is actually necessary to start the system,
and the earlier behavior obscured a packaging mistake.

diff --git a/debian/tree/zfs-initramfs/usr/share/initramfs-tools/hooks/zfs b/debian/tree/zfs-initramfs/usr/share/initramfs-tools/hooks/zfs
--- a/debian/tree/zfs-initramfs/usr/share/initramfs-tools/hooks/zfs
+++ b/debian/tree/zfs-initramfs/usr/share/initramfs-tools/hooks/zfs
@@ -27,6 +27,8 @@ COPY_EXEC_LIST="$COPY_EXEC_LIST /bin/hostname"
 # Explicitly specify all modules because dependency resolution is unreliable here.
 MANUAL_ADD_MODULES_LIST="zlib_deflate spl zavl zcommon znvpair zunicode zfs"
 
+# Generic result code.
+RC=0
 
 case $1 in
 prereqs)
@@ -37,8 +39,17 @@ esac
 
 for ii in $COPY_EXEC_LIST
 do
-	[ -x "$ii" ] || exit 0
+	if [ ! -x "$ii" ]
+	then
+		echo "Error: $ii is not executable."
+		RC=2
+	fi
 done
+
+if [ "$RC" -ne 0 ]
+then
+	exit "$RC"
+fi
 
 . /usr/share/initramfs-tools/hook-functions
 
