Turn the init.d scripts into autoconf config files so that @sbindir@ and @sysconfdir@ can be inserted from the config.

diff --git a/etc/init.d/zfs.fedora.in b/etc/init.d/zfs.fedora.in
--- a/etc/init.d/zfs.fedora.in
+++ b/etc/init.d/zfs.fedora.in
@@ -30,8 +30,9 @@ export PATH=/usr/local/sbin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
 
 # script variables
 RETVAL=0
-ZPOOL=zpool
-ZFS=zfs
+ZFS="@sbindir@/zfs"
+ZPOOL="@sbindir@/zpool"
+ZPOOL_CACHE="@sysconfdir@/zfs/zpool.cache"
 servicename=zfs
 LOCKFILE=/var/lock/subsys/$servicename
 
@@ -143,10 +144,10 @@ start()
 		fi
 	fi
 
-        if [ -f /etc/zfs/zpool.cache ] ; then
+        if [ -f $ZPOOL_CACHE ] ; then
 	
 		echo -n $"Importing ZFS pools not yet imported: "
-		$ZPOOL import -c /etc/zfs/zpool.cache -aN || true # stupid zpool will fail if all pools are already imported
+		$ZPOOL import -c $ZPOOL_CACHE -aN || true # stupid zpool will fail if all pools are already imported
 		RETVAL=$?
 		if [ $RETVAL -ne 0 ]; then
 			failure "Importing ZFS pools not yet imported: "
