Initial support for modern dracut versions
Signed-off-by: Andrew Tselischev <andrewtselischev@gmail.com>

diff --git a/dracut/90zfs/mount-zfs.sh.in b/dracut/90zfs/mount-zfs.sh.in
--- a/dracut/90zfs/mount-zfs.sh.in
+++ b/dracut/90zfs/mount-zfs.sh.in
@@ -1,71 +1,52 @@
 #!/bin/sh
 
-. /lib/dracut-lib.sh
+zpoolforce=""
+for p in $(getargs rd.zpool.force=) ; do
+	if [ "$p" = "1" ] ; then
+		zpoolforce="-f"
+	else
+		zpoolforce=""
+	fi
+done
 
-ZPOOL_FORCE=""
+if [ "${zfsroot}" = "true" ] ; then
+	udevsettle
+	if [ $seek_bootfs -eq 1 ] ; then
+		bootfs=`zpool list -H -o bootfs | sed -n '/-/ !p' | sed 'q'`
+		if [ "$?" != "0" ] || [ "$bootfs" = "no pools available" ] || [ -z "$bootfs" ] ; then
+			info "ZFS: Failed to get bootfs, trying more thoroughly"
+			zpool import -N -a "${zpoolforce}"
+			bootfs=`zpool list -H -o bootfs | sed -n '/-/ !p' | sed 'q'`
+			if [ "$?" != "0" ] || [ "$bootfs" = "" ] || [ $bootfs = "no pools available" ] ; then
+				rootok=0
+				die "ZFS: Failed to find bootfs, consider specifying it manually"
+				zpool list -H -o name | while read exppool ; do
+					zpool export "$exppool"
+				done
+			fi
+		fi
+	else
+		pool="${root%%/*}"
+		bootfs="${root}"
+		info "ZFS: pool = $pool"
+		info "ZFS: bootfs = $bootfs"
+		if ! zpool import -N "$zpoolforce" "$pool" ; then
+			warn "ZFS: unable to import pool $pool"
+			rootok=0
+		fi
+	fi
 
-if getargbool 0 zfs_force -y zfs.force -y zfsforce ; then
-	warn "ZFS: Will force-import pools if necessary."
-	ZPOOL_FORCE="-f"
+	mp=`zfs get -H -o value mountpoint $bootfs`
+	info "ZFS: mp = $mp"
+	info "ZFS: bootfs = $bootfs"
+	if [ "$mp" = "legacy" ] ; then
+		mount -o rw -t zfs "$bootfs" "$NEWROOT" && ROOT_MOUNTED=yes
+	else
+		mount -o rw,zfsutil -t zfs "$bootfs" "$NEWROOT" && ROOT_MOUNTED=yes
+	fi
+	if [ "$?" != "0" ] ; then
+		warn "ZFS: something went wrong while mounting root filesystem"
+	fi
+else
+	info "zfs not used"
 fi
-
-case "$root" in
-	zfs:*)
-		# We have ZFS modules loaded, so we're able to import pools now.
-		if [ "$root" = "zfs:AUTO" ] ; then
-			# Need to parse bootfs attribute
-			info "ZFS: Attempting to detect root from imported ZFS pools."
-
-			# Might be imported by the kernel module, so try searching before
-			# we import anything.
-			zfsbootfs=`zpool list -H -o bootfs | sed -n '/-/ !p' | sed 'q'`
-			if [ "$?" != "0" ] || [ "$zfsbootfs" = "" ] || \
-				[ "$zfsbootfs" = "no pools available" ] ; then
-				# Not there, so we need to import everything.
-				info "ZFS: Attempting to import additional pools."
-				zpool import -N -a ${ZPOOL_FORCE}
-				zfsbootfs=`zpool list -H -o bootfs | sed -n '/-/ !p' | sed 'q'`
-				if [ "$?" != "0" ] || [ "$zfsbootfs" = "" ] || \
-					[ "$zfsbootfs" = "no pools available" ] ; then
-					rootok=0
-					pool=""
-
-					warn "ZFS: No bootfs attribute found in importable pools."
-
-					# Re-export everything since we're not prepared to take
-					# responsibility for them.
-					zpool list -H | while read fs rest ; do
-						zpool export "$fs"
-					done
-
-					return 1
-				fi
-			fi
-			info "ZFS: Using ${zfsbootfs} as root."
-		else
-			# Should have an explicit pool set, so just import it and we're done.
-			zfsbootfs="${root#zfs:}"
-			pool="${zfsbootfs%%/*}"
-			if ! zpool list -H $pool > /dev/null ; then
-				# pool wasn't imported automatically by the kernel module, so
-				# try it manually.
-				info "ZFS: Importing pool ${pool}..."
-				if ! zpool import -N ${ZPOOL_FORCE} $pool ; then
-					warn "ZFS: Unable to import pool ${pool}."
-					rootok=0
-
-					return 1
-				fi
-			fi
-		fi
-
-		# Above should have left our rpool imported and pool/dataset in $root.
-		# We need zfsutil for non-legacy mounts and not for legacy mounts.
-		mountpoint=`zfs get -H -o value mountpoint $zfsbootfs`
-		if [ "$mountpoint" = "legacy" ] ; then
-			mount -t zfs "$zfsbootfs" "$NEWROOT" && ROOTFS_MOUNTED=yes
-		else
-			mount -o zfsutil -t zfs "$zfsbootfs" "$NEWROOT" && ROOTFS_MOUNTED=yes
-		fi
-		;;
-esac
