Fix import problems in Fedora 29.
In Fedora 29, a race condition causes the ZFS module not to be imported
before the unit file starts.  This patch fixes that condition.

Signed-off-by: Rudd-O <rudd-o@rudd-o.com>

diff --git a/contrib/dracut/90zfs/mount-zfs.sh.in b/contrib/dracut/90zfs/mount-zfs.sh.in
--- a/contrib/dracut/90zfs/mount-zfs.sh.in
+++ b/contrib/dracut/90zfs/mount-zfs.sh.in
@@ -34,12 +34,17 @@ info "ZFS: No sysroot.mount exists or zfs-generator did not extend it."
 info "ZFS: Mounting root with the traditional mount-zfs.sh instead."
 
 # Delay until all required block devices are present.
-modprobe zfs 2>/dev/null
+if ! modprobe zfs zfs_autoimport_disable=1 ; then
+	warn "ZFS: Unable to load zfs kernel module before settling udevadm."
+fi
 udevadm settle
 
 if [ "${root}" = "zfs:AUTO" ] ; then
 	ZFS_DATASET="$(find_bootfs)"
 	if [ $? -ne 0 ] ; then
+		if ! modprobe zfs zfs_autoimport_disable=1 ; then
+			warn "ZFS: Unable to load zfs kernel module while importing all pools."
+		fi
 		zpool import -N -a ${ZPOOL_IMPORT_OPTS}
 		ZFS_DATASET="$(find_bootfs)"
 		if [ $? -ne 0 ] ; then
diff --git a/contrib/dracut/90zfs/zfs-lib.sh.in b/contrib/dracut/90zfs/zfs-lib.sh.in
--- a/contrib/dracut/90zfs/zfs-lib.sh.in
+++ b/contrib/dracut/90zfs/zfs-lib.sh.in
@@ -60,6 +60,9 @@ find_bootfs() {
 import_pool() {
         pool="${1}"
 
+    if ! modprobe zfs zfs_autoimport_disable=1 ; then
+        warn "ZFS: Unable to load zfs kernel module while importing pool ${pool}."
+    fi
     if ! zpool list -H "${pool}" > /dev/null 2>&1; then
         info "ZFS: Importing pool ${pool}..."
         if ! zpool import -N ${ZPOOL_IMPORT_OPTS} "${pool}" ; then
